import type { $Enums } from "@prisma/client";

export type BookTag = $Enums.BookTag;

export const BookTagValues: BookTag[] = [
  "ROMANCE",
  "CONTO",
  "NARRATIVA",
  "FICCAO_NARRATIVA",
  "POESIA",
  "DRAMA",
  "MODERNISMO",
  "CONTEMPORANEO",
  "FANTASIA",
  "MISTERIO",
  "POLICIAL",
  "FICCAO",
  "NAO_FICCAO",
  "BIOGRAFIA",
  "AUTOBIOGRAFIA",
  "ROMANTISMO",
  "INFANTIL",
  "COMPORTAMENTO",
  "AUTOAJUDA",
  "CLASSICO",
  "TERROR",
  "SUSPENSE",
  "FICCAO_CIENTIFICA",
  "HORROR",
  "THRILLER",
  "COMEDIA",
  "CRONICA",
  "LITERATURA_INFANTOJUVENIL",
  "REGIONAL",
  "LITERATURA_FEMININA",
  "MEMORIAS",
  "OUTROS",
];

// Mapeamento de labels com acentuação/titulação correta para exibição
export const BookTagLabels: Record<BookTag, string> = {
  ROMANCE: "Romance",
  CONTO: "Conto",
  NARRATIVA: "Narrativa",
  FICCAO_NARRATIVA: "Ficção narrativa",
  POESIA: "Poesia",
  DRAMA: "Drama",
  MODERNISMO: "Modernismo",
  CONTEMPORANEO: "Contemporâneo",
  FANTASIA: "Fantasia",
  MISTERIO: "Mistério",
  POLICIAL: "Policial",
  FICCAO: "Ficção",
  NAO_FICCAO: "Não-ficção",
  BIOGRAFIA: "Biografia",
  AUTOBIOGRAFIA: "Autobiografia",
  ROMANTISMO: "Romantismo",
  INFANTIL: "Infantil",
  COMPORTAMENTO: "Comportamento",
  AUTOAJUDA: "Autoajuda",
  CLASSICO: "Clássico",
  TERROR: "Terror",
  SUSPENSE: "Suspense",
  FICCAO_CIENTIFICA: "Ficção científica",
  HORROR: "Horror",
  THRILLER: "Thriller",
  COMEDIA: "Comédia",
  CRONICA: "Crônica",
  LITERATURA_INFANTOJUVENIL: "Literatura infantojuvenil",
  REGIONAL: "Regional",
  LITERATURA_FEMININA: "Literatura feminina",
  MEMORIAS: "Memórias",
  OUTROS: "Outros",
};
