export const BookTagValues = [
  'TROVADORISMO', 'CLASSICISMO', 'BARROCO', 'ARCADISMO', 'ROMANTISMO', 'REALISMO', 'NATURALISMO', 'PARNASIANISMO', 'SIMBOLISMO', 'PRE_MODERNISMO', 'MODERNISMO', 'POS_MODERNISMO', 'CONTEMPORANEO',
  'FICCAO_CIENTIFICA', 'FANTASIA', 'HORROR', 'THRILLER', 'POLICIAL', 'DRAMA', 'COMEDIA', 'POESIA', 'CRONICA', 'LITERATURA_INFANTOJUVENIL',
  'REGIONAL', 'LITERATURA_FEMININA', 'BIOGRAFIA', 'MEMORIAS', 'AUTO_AJUDA', 'OUTROS'
] as const;

export type BookTag = (typeof BookTagValues)[number];
